In [1]:
import gym
import numpy as np
from active_critic.utils.gym_utils import make_dummy_vec_env

/home/hendrik/miniconda3/envs/ac/lib/python3.10/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [2]:
class Reach1D(gym.Env):
    def __init__(self) -> None:
        super().__init__()
        self.action_space = gym.spaces.Box(np.array([-1]), np.array([1]))
        self.observation_space = gym.spaces.Box(np.array([-1]), np.array([1]))
        self._reset()

    def _reset(self):
        self.position = np.array([-0.5])
        self.goal = np.array([0.5])

    def step(self, action):
        action = np.minimum(action, self.action_space.high)
        action = np.maximum(action, self.action_space.low)
        self.position = self.position + 0.1 * action
        self.position = np.minimum(self.position, self.observation_space.high)
        self.position = np.maximum(self.position, self.observation_space.low)

        reward = 1 - (self.position - self.goal)**2
        success = reward > 0.9
        return self.position, reward, success, {}

    def reset(self):
        self._reset()
        return self.position


In [3]:
r1de = Reach1D()

/home/hendrik/miniconda3/envs/ac/lib/python3.10/site-packages/gym/spaces/box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(


In [4]:
dr1d, _ = make_dummy_vec_env('test', seq_len=20, env=r1de)

In [5]:
dr1d.reset()

array([[-0.5]], dtype=float32)

In [6]:
for i in range(20):
    print(dr1d.step(np.array([0.5])))

(array([[-0.45]], dtype=float32), array([0.0975], dtype=float32), array([False]), [{}])
(array([[-0.4]], dtype=float32), array([0.19], dtype=float32), array([False]), [{}])
(array([[-0.35]], dtype=float32), array([0.2775], dtype=float32), array([False]), [{}])
(array([[-0.3]], dtype=float32), array([0.36], dtype=float32), array([False]), [{}])
(array([[-0.25]], dtype=float32), array([0.4375], dtype=float32), array([False]), [{}])
(array([[-0.19999999]], dtype=float32), array([0.51], dtype=float32), array([False]), [{}])
(array([[-0.14999999]], dtype=float32), array([0.5775], dtype=float32), array([False]), [{}])
(array([[-0.09999999]], dtype=float32), array([0.64], dtype=float32), array([False]), [{}])
(array([[-0.04999999]], dtype=float32), array([0.6975], dtype=float32), array([False]), [{}])
(array([[7.450581e-09]], dtype=float32), array([0.75], dtype=float32), array([False]), [{}])
(array([[0.05000001]], dtype=float32), array([0.7975], dtype=float32), array([False]), [{}])
(array([